import { NextResponse } from 'next/server';

export async function GET() {
  // Pre-configured posts with direct live Instagram CDN images
  const defaultPosts = [
    { id: 1, image: '/api/instagram/image?code=DZsCsz3zFuw', likes: 254, commentsCount: 14, link: 'https://www.instagram.com/p/DZsCsz3zFuw/', caption: 'XAUUSD (GOLD) market analysis is live. Plan your entry targets with our raw spreads. 📈', comments: [{ user: 'trader_dubai', text: 'Clean charting! Spreads are very tight.' }, { user: 'capital_forex', text: 'Caught the gold breakout today. MT5 is flawless.' }] },
    { id: 2, image: '/api/instagram/image?code=DWjMCE4kXYt', likes: 198, commentsCount: 9, link: 'https://www.instagram.com/p/DWjMCE4kXYt/', caption: 'Capital security remains our primary asset. Segregated Tier-1 account protocols are active. 🛡️', comments: [{ user: 'safetrade_inc', text: 'Segregated accounts are a must. Respect.' }, { user: 'vip_trader_ae', text: 'Smooth deposit and fast withdrawal processing.' }] },
    { id: 3, image: '/api/instagram/image?code=DWguJd0E-nK', likes: 312, commentsCount: 19, link: 'https://www.instagram.com/p/DWguJd0E-nK/', caption: 'ECN execution parameters: raw spreads from 0.0 pips, institutional depth of market. ⚡', comments: [{ user: 'scalper_pro', text: 'Zero markup is real on the ECN account.' }, { user: 'market_maker', text: 'Less than 15ms latency. Insane!' }] },
    { id: 4, image: '/api/instagram/image?code=DWY38TfE0im', likes: 167, commentsCount: 11, link: 'https://www.instagram.com/p/DWY38TfE0im/', caption: 'Trade global markets on the go. Full MT5 dashboard available for iOS and Android. 📱', comments: [{ user: 'nomad_trader', text: 'The mobile app interface is super clean.' }, { user: 'mt5_fan', text: 'Execution speed on mobile is very fast.' }] },
    { id: 5, image: '/api/instagram/image?code=DWWeWySk5v1', likes: 210, commentsCount: 8, link: 'https://www.instagram.com/p/DWWeWySk5v1/', caption: 'Discipline beats strategy. Stay in the game and protect your capital with Magnate. ⚜️', comments: [{ user: 'growth_mindset', text: 'Patience win the race. Solid quote!' }, { user: 'risk_mgmt', text: 'Patience is everything in forex.' }] },
    { id: 6, image: '/api/instagram/image?code=DWTt9cmEzro', likes: 182, commentsCount: 12, link: 'https://www.instagram.com/p/DWTt9cmEzro/', caption: 'Market watch structures update. Focus on high-probability setups and manage risk. 📊', comments: [{ user: 'technical_fx', text: 'Daily market outlook has been very helpful.' }, { user: 'pips_hunter', text: 'AUDUSD is looking hot this week.' }] },
    { id: 7, image: '/api/instagram/image?code=DWRJF4XE9xd', likes: 289, commentsCount: 16, link: 'https://www.instagram.com/p/DWRJF4XE9xd/', caption: 'Elite conditions for high-volume traders. Direct Liquidity access and raw margins. 💼', comments: [{ user: 'hedgefund_ae', text: 'Great ECN conditions for bulk orders.' }, { user: 'forex_whale', text: 'Top broker service in Dubai Currency House!' }] },
    { id: 8, image: '/api/instagram/image?code=DWOVzjXDR0M', likes: 143, commentsCount: 6, link: 'https://www.instagram.com/p/DWOVzjXDR0M/', caption: 'Official registration callback desk is active. Connect with our dedicated VIP desk. 📞', comments: [{ user: 'broker_advisor', text: 'Top customer desk support.' }, { user: 'al_fattan_client', text: 'Dubai office has been helpful.' }] }
  ];

  return NextResponse.json({ success: true, posts: defaultPosts });
}
